### ISSUE TITLE
Setup CI/CD

### ISSUE THREAD

**Issue by praburangki** [gdg-bali/webapp#20]

**Comment by deerawan** [comment]
@praburangki what CI/CD are we going to use? Travis CI?

**Comment by alexcnichols** [comment]
Hey, I noticed this issue in the hacktoberfest search. Consider trying Azure Pipelines, which is free for open source projects. https://github.com/marketplace/azure-pipelines

Also, it looks like you were building using Yarn and Travis at one point. In case you run into trouble, here is a related discussion about using the Azure Pipelines Linux build agent. https://github.com/Microsoft/azure-pipelines-image-generation/issues/236

**Comment by praburangki** [comment]
@deerawan I was intended to use travis but haven't got any success yet. Since this is a clone from [this boilerplate](https://github.com/chrisvfritz/vue-enterprise-boilerplate), there's already a circleci config. So either it's okay.

@alexcnichols awesome, will take a look at that. Thanks!

**Comment by deerawan** [comment]
@alexcnichols cool! never heard about azure pipelines before. 

@praburangki let me check on that.

**Comment by deerawan** [comment]
@praburangki ~I want to try the circle ci first. Have we added circle CI app to this project? https://github.com/marketplace/circleci~

Update:
nevermind, I saw this PR triggered circle ci. https://github.com/gdg-bali/webapp/pull/30

@praburangki any idea why the CI is not triggered for this PR https://github.com/gdg-bali/webapp/pull/31?

**Comment by praburangki** [comment]
@deerawan 
hi, i've updated the circleci config and removed travis and it's already in the develop branch.
but the build is still failing.
maybe you can help to solve this issue.
Thanks!

**Comment by deerawan** [comment]
@praburangki I removed the travis CI already in my PR, however I didn't see the CI running on this branch.

Here is screenshot of mine

![image](https://user-images.githubusercontent.com/1243921/47014980-febd5580-d175-11e8-8be4-ca91a9ea2e77.png)

> but the build is still failing.

where did you see it? 

UPDATE:
I'll try to setup CircleCI for my account. Maybe this is the solution.

**Comment by deerawan** [comment]
@praburangki it is fixed 
https://github.com/gdg-bali/webapp/pull/31
